#!/bin/sh

SERVER=$1

if [ "$SERVER" == "" ]; then
  echo "Available servers: ${SERVERS}"
  exit 0
fi

if [ "$BIND_IP" != "" ]; then
  ssh -b ${BIND_IP} -p 2222 root@$SERVER
elif [ "$BIND_IFACE" != "" ]; then
  ssh -B ${BIND_IFACE} -p 2222 root@$SERVER
else
  ssh -p 2222 root@$SERVER
fi

exit $?
